/* EULER PROBLEM 2
* 
* Each new term in the Fibonacci sequence is generated by
* adding the previous two terms. By starting with 1 and 2, the
* first 10 terms will be:
* 
* 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
* 
* By considering the terms in the Fibonacci sequence whose
* values do not exceed four million, find the sum of the
* even-valued terms.
* 
* Author: River Gillis
*/

var sum = 0;
var prevTerm1 = 1;
var prevTerm2 = 1;
var newTerm = 1;

while (newTerm < 4000000) {
    if (newTerm % 2 === 0) {
        sum += newTerm
    }
    
    prevTerm2 = prevTerm1;
    prevTerm1 = newTerm;
    newTerm = prevTerm1 + prevTerm2;
}

console.log(sum);

